### ISSUE TITLE
':dexDebug FAILED' from your AmazonMobileAds plugin

### ISSUE THREAD

**Issue by RGVida** [blakgeek/cordova-plugin-amazonmobileads#5]
Using this directly onto a freshly made Cordova project produces the following error:

C:\CORDOVA\admob\amazonBG>cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.raphaelrios.amazonBG
        Name: HelloCordova
        Activity: MainActivity
        Android target: android-22
Copying template files...
Android project created with cordova-android@4.1.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the pr
oject
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android

C:\CORDOVA\admob\amazonBG>cordova plugin add https://github.com/blakgeek/cordova
-plugin-amazonmobileads
Fetching plugin "https://github.com/blakgeek/cordova-plugin-amazonmobileads" via
 git clone
Repository "https://github.com/blakgeek/cordova-plugin-amazonmobileads" checked
out to git ref "master".
Installing "com.blakgeek.cordova.plugin.amazonmobileads" for android
Fetching plugin "com.google.playservices" via npm
Installing "com.google.playservices" for android

C:\CORDOVA\admob\amazonBG>cordova build android
Running command: cmd "/s /c "C:\CORDOVA\admob\amazonBG\platforms\android\cordova
\build.bat""
ANDROID_HOME=C:\Users\TSHB\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_51
Running: C:\CORDOVA\admob\amazonBG\platforms\android\gradlew cdvBuildDebug -b C:
\CORDOVA\admob\amazonBG\platforms\android\build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk
:preDebugBuild
:checkDebugManifest
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:com.google.playservices:google-play-services_lib:compileLint
:com.google.playservices:google-play-services_lib:copyDebugLint UP-TO-DATE
:com.google.playservices:google-play-services_lib:mergeDebugProguardFiles
:com.google.playservices:google-play-services_lib:preBuild
:com.google.playservices:google-play-services_lib:preDebugBuild
:com.google.playservices:google-play-services_lib:checkDebugManifest
:com.google.playservices:google-play-services_lib:preDebugTestBuild
:com.google.playservices:google-play-services_lib:prepareAndroidCordovaLibUnspec
ifiedDebugLibrary
:com.google.playservices:google-play-services_lib:prepareDebugDependencies
:com.google.playservices:google-play-services_lib:compileDebugAidl
:com.google.playservices:google-play-services_lib:compileDebugRenderscript
:com.google.playservices:google-play-services_lib:generateDebugBuildConfig
:com.google.playservices:google-play-services_lib:generateDebugAssets UP-TO-DATE

:com.google.playservices:google-play-services_lib:mergeDebugAssets
:com.google.playservices:google-play-services_lib:generateDebugResValues
:com.google.playservices:google-play-services_lib:generateDebugResources
:com.google.playservices:google-play-services_lib:mergeDebugResources
:com.google.playservices:google-play-services_lib:processDebugManifest
:com.google.playservices:google-play-services_lib:processDebugResources
warning: string 'common_android_wear_notification_needs_update_text' has no defa
ult translation.
warning: string 'common_android_wear_update_text' has no default translation.
warning: string 'common_android_wear_update_title' has no default translation.
warning: string 'common_open_on_phone' has no default translation.
:com.google.playservices:google-play-services_lib:generateDebugSources
:com.google.playservices:google-play-services_lib:compileDebugJava
:com.google.playservices:google-play-services_lib:processDebugJavaRes UP-TO-DATE

:com.google.playservices:google-play-services_lib:packageDebugJar
:com.google.playservices:google-play-services_lib:compileDebugNdk
:com.google.playservices:google-play-services_lib:packageDebugJniLibs UP-TO-DATE

:com.google.playservices:google-play-services_lib:packageDebugLocalJar
:com.google.playservices:google-play-services_lib:packageDebugRenderscript UP-TO
-DATE
:com.google.playservices:google-play-services_lib:packageDebugResources
:com.google.playservices:google-play-services_lib:bundleDebug
:prepareAndroidComGooglePlayservicesGooglePlayServices_libUnspecifiedDebugLibrar
y
:prepareAndroidCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
warning: string 'common_android_wear_notification_needs_update_text' has no defa
ult translation.
warning: string 'common_android_wear_update_text' has no default translation.
warning: string 'common_android_wear_update_title' has no default translation.
warning: string 'common_open_on_phone' has no default translation.
:generateDebugSources
:compileDebugJava
:preDexDebug
:dexDebug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/ads/AdReques
t$ErrorCode;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:50
2)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':dexDebug'.
  
  > com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  >     C:\Users\TSHB\AppData\Local\Android\sdk\build-tools\23.0.1\dx.bat --dex
  > --no-optimize --output C:\CORDOVA\admob\amazonBG\platforms\android\build\interme
  > diates\dex\debug --input-list=C:\CORDOVA\admob\amazonBG\platforms\android\build\
  > intermediates\tmp\dex\debug\inputList.txt
  > Error Code:
  >     2
  > Output:
  
  ```
  UNEXPECTED TOP-LEVEL EXCEPTION:
  com.android.dex.DexException: Multiple dex files define Lcom/google/ads/
  ```
  
  AdRequest$ErrorCode;
              at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.ja
  va:596)
              at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:
  554)
              at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:
  535)
              at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
  
  ```
          at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
          at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main
  ```
  
  .java:502)
              at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
              at com.android.dx.command.dexer.Main.run(Main.java:277)
              at com.android.dx.command.dexer.Main.main(Main.java:245)
              at com.android.dx.command.Main.main(Main.java:106)
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED

Total time: 1 mins 25.695 secs

C:\CORDOVA\admob\amazonBG\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "C:\CORDOVA\admob\amazonBG\platfo
rms\android\gradlew cdvBuildDebug -b C:\CORDOVA\admob\amazonBG\platforms\android
\build.gradle -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 1

You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 1
    at ChildProcess.whenDone (C:\Users\TSHB\AppData\Roaming\npm\node_modules\cor
dova\node_modules\cordova-lib\src\cordova\superspawn.js:139:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

I've read that older plugins may not build correctly due to the CLI-5 + from Cordova. Is there something I need to add or remove from this setup? Any insight would be appreciated. Thank you, Raphael

**Comment by blakgeek** [comment]
I updated the plugin.xml to use gradle for managing the dependencies.  That should address your issue.  Let me know if you're still having problems.

**Comment by RGVida** [comment]
Thank you so much for that update. The build was successful with no failures or errors.

**Comment by RGVida** [comment]
How can I implement a refresh rate for Amazon Mobile Ads or is there a default time? I use Cordova CLI to create my ad, so I need to implement it on the index.html inside where the rest of your AmazonMobileAds script. Any guidance is much appreciated. Thanks.
