### ISSUE TITLE
Gradle Error:Execution failed for task ':transformClassesWithMultidexlistForDebug'

### ISSUE THREAD

**Issue by f18nfz** [blakgeek/cordova-plugin-amazonmobileads#6]
After adding the plugin, when compiling I get the following error:

Error:Execution failed for task ':transformClassesWithMultidexlistForDebug'.

> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_67\bin\java.exe'' finished with non-zero exit value 1

I have tried to adding multiDexEnabled true to defaultConfig but this hasn't resolved the issue... I am using Gradle to build - any ideas why I get this after adding the plugin?

**Comment by f18nfz** [comment]
Figured out the issue, it was a conflict with the Android Support Library, the jar was already present in my project and so I have updated the gradle file and commented out the line to compile android support library to resolve this issue.

**Comment by blakgeek** [comment]
@f18nfz You should try to avoid modifying build.gradle directly because your changes will get overwritten.  Instead add a file named build-extras.gradle to the android platform's root directory (<project root>/platforms/android) containing the following.

```
configurations {
    all*.exclude group: 'com.android.support'
}
```

This will resolve your issue.
